name: Build TWRP for Smart 8
on:
  workflow_dispatch: # Para ikaw ang mag-trigger manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install git python3 openjdk-11-jdk-headless -y

      - name: Sync TWRP Source
        run: |
          mkdir twrp && cd twrp
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          # Gamit tayo ng minimal manifest (mga 30GB lang)
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc)

      - name: Clone Device Tree
        run: |
          cd twrp
          git clone https://github.com/twrpdtgen/android_device_infinix_Infinix-X6525 device/infinix/Infinix-X6525

      - name: Build Recovery
        run: |
          cd twrp
          source build/envsetup.sh
          lunch twrp_Infinix-X6525-eng
          mka recoveryimage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-Smart8-Image
          path: twrp/out/target/product/Infinix-X6525/recovery.img
